# Site-wide settings
title: Sameer’s Java Blog
description: >
  Real-world Java DSA, OOP, and backend learning journey with business use-case mapping.
author:
  name: Md Sameer
  email: your-email@example.com

# Build settings
remote_theme: jekyll/minima@d4d779a  # ✅ pinned to a stable commit
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima-specific settings
minima:
  skin: auto
  show_excerpts: true
  date_format: "%b %d, %Y"
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/raZer99"

# Optional Sass setting to silence warnings
sass:
  quiet_deps: true
